version: '3.9'
services:
  java_db:
    container_name: java_db
    image: 'postgres:latest'
    ports:
      - 5432:5432
    networks:
      - challenge
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: postgres

  account_app:
    container_name: account_app
    image: account:1.0.0
    build:
      context: .
    ports:
      - 8081:8081
    networks:
      - challenge
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=1234
    depends_on:
      - java_db

  client_app:
    container_name: client_app
    image: client:1.0.0
    build:
      context: ../NttData-app-client
    ports:
      - 8080:8080
    networks:
      - challenge
    environment:
      - SPRING_DATABASE_URL=jdbc:postgresql://java_db:5432/postgres
      - SPRING_DATABASE_USERNAME=postgres
      - SPRING_DATABASE_PASSWORD=1234

networks:
  challenge: